backend:
  name: github
  repo: KzonDada/PorteFolioo
  branch: main              

media_folder: "static/uploads"  
public_folder: "/uploads"      

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"     # dossier où on va stocker les fichiers Markdown pour les pages éditables
    create: true                # permet de créer de nouvelles pages depuis l’interface
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}